"""
Planner: map user question → intent, discover tables (marts first, then raw).
Returns candidates only; SQL is generated by the LLM (no hardcoded templates).
"""
from __future__ import annotations

import re
from typing import Any, List, Optional

from . import tools as copilot_tools
from .defaults import get_discover_tables_limit


def _extract_intent(question: str, context: Optional[List[dict]] = None) -> str:
    """Short intent phrase from the user question."""
    text = (question or "").strip().lower()
    if not text:
        return "analytics"
    stop = {
        "the", "a", "an", "is", "are", "was", "were", "what", "how", "many", "much",
        "for", "from", "to", "of", "in", "on", "at", "can", "you", "me", "my", "i", "we",
        "this", "that", "it", "and", "or", "but", "which", "that", "those", "these",
    }
    words = re.findall(r"\w+", text)
    kept = [w for w in words if w not in stop and len(w) > 1][:20]
    return " ".join(kept) if kept else "analytics"


def analyze(
    question: str,
    context: Optional[List[dict]] = None,
    client_id: Optional[int] = None,
    organization_id: str = "",
) -> dict:
    """
    Intent → discover_tables (marts first, synonym-aware) → candidates only.
    Returns { intent, candidates }. SQL is generated by the LLM from these candidates.
    """
    intent = _extract_intent(question, context)
    limit = get_discover_tables_limit()
    candidates_raw = copilot_tools.discover_tables(intent, limit=limit)
    project = _get_project()
    candidates = []
    for c in candidates_raw[:12]:
        proj = c.get("project") or project
        ds = c.get("dataset") or ""
        tbl = c.get("table") or c.get("table_name") or ""
        if not tbl:
            continue
        full = f"{proj}.{ds}.{tbl}"
        cols = c.get("columns") or []
        candidates.append({"table": full, "columns": cols})
    return {
        "intent": intent,
        "candidates": candidates,
    }


def _get_project() -> str:
    try:
        from ..clients.bigquery import _project
        return _project()
    except Exception:
        import os
        return os.environ.get("BQ_PROJECT", "")


def replan(
    question: str,
    failed_sql: Optional[str] = None,
    context: Optional[List[dict]] = None,
    client_id: Optional[int] = None,
    organization_id: str = "",
) -> dict:
    """Re-plan: same as analyze (returns fresh candidates). Optionally exclude failed_sql from context for LLM."""
    return analyze(question, context=context, client_id=client_id, organization_id=organization_id)
